=== kapilojha8/Rule-Engine/data/Lenders XML/pepper_loans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Root Element -->
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <!-- Field_type Element -->
                <xs:element name="Field_type">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="FT_0" type="xs:string" />
                            <xs:element name="FT_1" type="xs:string" />
                            <xs:element name="FT_2" type="xs:string" />
                            <xs:element name="FT_3" type="xs:string" />
                            <xs:element name="FT_4" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Remarks Element -->
                <xs:element name="Remarks">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="R1" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Lenders Element -->
                <xs:element name="Lenders">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Flexi_up_to_20K Element -->
                            <xs:element name="Flexi_up_to_20K">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- Asset_Type Element -->
                                        <xs:element name="Asset_Type">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Flow_Exception_for_True"
                                                        minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:attribute name="Condition_to_proceed" type="xs:string" use="required" />
                                                            <xs:attribute name="Remark" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Flow_Exception_for_False"
                                                        minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence> 
                                                                <xs:element name="Exception_rule"  minOccurs="0" maxOccurs="1">     
                                                                    <xs:complexType> 
                                                                        <xs:sequence>
                                                                            <xs:element
                                                                                name="Flow_Exception_for_True"
                                                                                minOccurs="0"
                                                                                maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:attribute
                                                                                        name="Remark"
                                                                                        type="xs:string"
                                                                                        use="required" />
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                            <xs:element
                                                                                name="Flow_Exception_for_False"
                                                                                minOccurs="0"
                                                                                maxOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:attribute
                                                                                        name="Remark"
                                                                                        type="xs:string"
                                                                                        use="required" />
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute
                                                                            name="Reference_field"
                                                                            type="xs:string"
                                                                            use="required" />
                                                                        <xs:attribute
                                                                            name="Rule_Operator"
                                                                            type="xs:string"
                                                                            use="required" />
                                                                        <xs:attribute
                                                                            name="Field_Type"
                                                                            type="xs:string"
                                                                            use="required" />
                                                                        <xs:attribute
                                                                            name="Rule_Value"
                                                                            type="xs:string"
                                                                            use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute
                                                                name="Condition_to_proceed"
                                                                type="xs:string" use="required" />
                                                            <xs:attribute name="Remark"
                                                                type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="Reference_field"
                                                    type="xs:string" use="required" />
                                                <xs:attribute name="Rule_Operator" type="xs:string"
                                                    use="required" />
                                                <xs:attribute name="Field_Type" type="xs:string"
                                                    use="required" />
                                                <xs:attribute name="Rule_Value" type="xs:string"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>

                                        <!-- ABN_Registration Element -->
                                        <xs:element name="ABN_Registration">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Flow_Exception_for_True">
                                                        <xs:complexType>
                                                            <xs:attribute
                                                                name="Condition_to_proceed"
                                                                type="xs:boolean" use="required" />
                                                            <xs:attribute name="Remark" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Flow_Exception_for_False">
                                                        <xs:complexType>
                                                            <xs:attribute name="Condition_to_proceed" type="xs:boolean" use="required" />
                                                            <xs:attribute name="Remark" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="Reference_field" type="xs:string" use="required" />
                                                <xs:attribute name="Rule_Operator" type="xs:string" use="required" />
                                                <xs:attribute name="Rule_Value" type="xs:string" use="required" />
                                                <xs:attribute name="Field_Type" type="xs:string" use="required" />
                                            </xs:complexType>
                                        </xs:element>

                                        <!-- GST_Registration Element -->
                                        <xs:element name="GST_Registration">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Flow_Exception_for_True">
                                                        <xs:complexType>
                                                            <xs:attribute name="Condition_to_proceed" type="xs:boolean" use="required" />
                                                            <xs:attribute name="Remark" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Flow_Exception_for_False">
                                                        <xs:complexType>
                                                            <xs:attribute name="Condition_to_proceed" type="xs:boolean" use="required" />
                                                            <xs:attribute name="Remark" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="Reference_field"
                                                    type="xs:string" use="required" />
                                                <xs:attribute name="Rule_Operator" type="xs:string"
                                                    use="required" />
                                                <xs:attribute name="Rule_Value" type="xs:string"
                                                    use="required" />
                                                <xs:attribute name="Field_Type" type="xs:string"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>

                                        <!-- Loan_Amount Element -->
                                        <xs:element name="Loan_Amount">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Logical_Rule">
                                                        <xs:complexType>
                                                            <xs:attribute name="Reference_field" type="xs:string" use="required" />
                                                            <xs:attribute name="Rule_Operator" type="xs:string" use="required" />
                                                            <xs:attribute name="Rule_Value" type="xs:string" use="required" />
                                                            <xs:attribute name="Field_Type" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Flow_Exception_for_True">
                                                        <xs:complexType>
                                                            <xs:attribute name="Condition_to_proceed" type="xs:boolean" use="required" />
                                                            <xs:attribute name="Remark" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Flow_Exception_for_False">
                                                        <xs:complexType>
                                                            <xs:attribute name="Condition_to_proceed" type="xs:boolean" use="required" />
                                                            <xs:attribute name="Remark" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="Reference_field"
                                                    type="xs:string" use="required" />
                                                <xs:attribute name="Rule_Operator" type="xs:string"
                                                    use="required" />
                                                <xs:attribute name="Rule_Value" type="xs:string"
                                                    use="required" />
                                                <xs:attribute name="Field_Type" type="xs:string"
                                                    use="required" />
                                                <xs:attribute name="logical_operator"
                                                    type="xs:string" />
                                            </xs:complexType>
                                        </xs:element>

                                        <!-- Continue defining other elements like ABN_Registration,
                                        Loan_Amount, etc. -->
                                    </xs:sequence>

                                    <!-- Attributes for Flexi_up_to_20K -->
                                    <xs:attribute name="Some_Attribute" type="xs:string"
                                        use="optional" />
                                    <xs:attribute name="Another_Attribute" type="xs:string"
                                        use="optional" />

                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kapilojha8/Rule-Engine/data/Lenders XML/Pepper Loans.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="pepper_loans.xsd">
    <Field_type>
        <FT_0>bool</FT_0>
        <FT_1>date</FT_1>
        <FT_2>float</FT_2>
        <FT_3>int</FT_3>
        <FT_4>str</FT_4>
    </Field_type>
    <Remarks>
        <R1> Benefit of Doubt </R1>
    </Remarks>
    <Lenders>
        <Flexi_up_to_20K>
            <Asset_Type Reference_field="asset_type" Rule_Operator="in" Field_Type="4"
                Rule_Value="Agricultural machinery and equipment, Materials handling/forklifts, Access equipment (boom/scissor lifts), Light trucks &lt;3.5 tonnes, Heavy trucks &gt;3.5 tonnes, TRAILERS, BUSES AND COACHES, Commercial Motor_Vehicles (utes, vans and 4WDs), Construction and earth moving equipment (non-mining)">
                <Flow_Exception_for_True Condition_to_proceed="true"
                    Remark="The asset is listed as an eligible asset." />
                <Flow_Exception_for_False Condition_to_proceed="false"
                    Remark="There are no applicable asset categories for this asset. Consequently, checking the 'Excluded asset list'.">
                    <Exception_rule Reference_field="asset_type" Rule_Operator="not in"
                        Field_Type="4" Rule_Value="Passenger cars, SUVs">
                        <Flow_Exception_for_True
                            Remark="The asset is not listed as excluded on any applicable list. As a result, it will be given the benefit of the doubt for additional evaluation." />
                        <Flow_Exception_for_False
                            Remark="The asset qualifies in excluded asset list and will not be considered for further assessment." />
                    </Exception_rule>
                </Flow_Exception_for_False>
            </Asset_Type>

            <ABN_Registration Reference_field="ABN_in_Months" Rule_Operator="&gt;=" Rule_Value="24"
                Field_Type="3">
                <Flow_Exception_for_True Condition_to_proceed="true"
                    Remark="The borrower meets the age requirement of ABN for the relevant asset categories." />
                <Flow_Exception_for_False Condition_to_proceed="false"
                    Remark="The borrower does not meet the age requirement of ABN for the relevant asset categories." />
            </ABN_Registration>

            <GST_Registration Reference_field="GST_in_Months" Rule_Operator="&gt;=" Rule_Value="0"
                Field_Type="3">
                <Flow_Exception_for_True Condition_to_proceed="true"
                    Remark="The borrower business meets the age requirement of GST for the relevant asset categories." />
                <Flow_Exception_for_False Condition_to_proceed="false"
                    Remark="The borrower business does not meet the age requirement of GST for the relevant asset categories." />
            </GST_Registration>

            <Loan_Amount Reference_field="amount_financed" Rule_Operator="&lt;=" Rule_Value="20000"
                Field_Type="3" logical_operator="and">
                <Logical_Rule Reference_field="amount_financed" Rule_Operator="&gt;" Rule_Value="0"
                    Field_Type="3" />
                <Flow_Exception_for_True Condition_to_proceed="true"
                    Remark="The loan limit meets the criteria for the relevant asset categories." />
                <Flow_Exception_for_False Condition_to_proceed="false"
                    Remark="The loan limit does not meet the criteria for loan range for the relevant asset categories." />
            </Loan_Amount>
        </Flexi_up_to_20K>


    </Lenders>


</root>
